services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grocery_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/grocery
      REDIS_URL: redis://redis:6379
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./screenshots:/app/screenshots
      - /app/node_modules
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: grocery_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7.4
    container_name: grocery_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  redis_data:
